inherit SKILL;

mapping *quest = ({
	([	"quest":	"ºó±¸±ø",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"¾üµ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"Öª¿ÍµÀ³¤",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"[30m¶ñ°Ô[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"ÕÔ¹·¶ù",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[31mÃÅ·¿[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Çå¹Û±ÈÇð",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"ÇåÀÖ±ÈÇð",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"ÇåÎª±ÈÇð",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"ÇåÔµ±ÈÇð",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"°×²¼ºÚ±ßôÂôÄ",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"½£¿Í",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"ïÚÊ¦",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"»¤ËÂ²ØÄá",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"´óºìÄáÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"°¢À­Ä¾º±",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"ð±Ä¸",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"¼«ÀÖåÐÒ£É¢",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Ð¡´ä",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Ðå»¨Ð¡Ð¬",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Ï¸½£",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36mÇàÒÂÉÙÅ®[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36mÇàÐ¬[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36mÇàïí[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36mÇàÒÂ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36mÇà´ø[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36mÇàÃ±[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36mÇà½í[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Ð¡±ø",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"ÀÏ±ø",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"´¬·ò",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"»¤ÁÖÉ®±ø",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"½äµ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"Ö£ÍÀ·ò",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"½âÅ£µ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"Å£Æ¤Êø´ø",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"ÇàÒÂÉÙÅ®",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[30mÁºÍòÁ¼[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"ÇàÒÂ",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Çà´ø",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"ÀÏ´¬·ò",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"ÍõÐ¡¶þ",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"ÇåÎÞ±ÈÇð",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"ÕÅÊ¢",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"³ÇÎÀ",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Èý»·ìøÕÈ",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"´óºìÉ®ÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Ü½ÔÆ",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"¿Õ¿Õ¶ù",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"ÕÅ²ýÊ¤",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"ÍõÊ¢ÐÛ",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"ÕÅÁú¶°",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"ËïÊÙÒÚ",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Ä¾ÈË",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Ô°¶¡",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"ÇåÉÆ±ÈÇð",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"ÇåÎÅ±ÈÇð",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"ÇåÏþ±ÈÇð",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"[33m×óÃ÷Öé[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"ÂòÂôÌá",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"Å·Ñô¿Ë",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"ÀÏÆÅ×Ó",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m»ÆÒÂÉÙÅ®[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m»ÆÐ¬[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m»Æïí[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m»ÆÒÂ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m»Æ´ø[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m»ÆÃ±[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m»Æ½í[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"³ø×Ó",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"±ÌÓñµ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"¿¾É½ÖíÈâ",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"ÈËÆ¤¾Æ´ü",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"ÐéÃ÷",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"ÞÄÕß",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Æå×Ó",
		"quest_type":	"Ñ°",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"Ò°Öí",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"²ÝÔ­ÀÇ",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"¾ÞÐÍÈ®",
		"quest_type":	"É±",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
