#include <ansi.h>
inherit SKILL;
mapping *quest=({
(["quest": "苗人风",
  "quest_type": "杀",
  "time":    "400",
  "exp_bonus": 80,
  "pot_bonus": 20,
  "score": 15,
]),
(["quest": "摘星子",
  "quest_type": "杀",
  "time":      450,
  "exp_bonus": 100,
  "pot_bonus": 25,
  "score":    20,
]),
(["quest":   "日后",
 "quest_type": "杀",
 "time":     550,
 "exp_bonus": 80,
 "pot_bonus": 30,
 "score": 15,
]),
(["quest":    MAG"穆桂英"NOR,
  "quest_type": "杀",
  "time":     500,
  "exp_bonus": 100,
  "pot_bonus": 30,
  "score":    10,
]),
(["quest":  "江小川",
  "quest-type": "杀",
  "time": 450,
  "exp_bonus": 20,
  "pot_bonus": 10,
  "score":     9,
]),
([
  "quest":     BLK"大理石"NOR,
  "quest_type": "寻",
  "time":       500,
  "exp_bonus":  20,
  "pot_type":   10,
  "score":      5,
]),
(["quest":  MAG "郭啸天" NOR,
  "quest":    "杀",
  "time":     350,
 "exp_bonus": 30,
  "pot_bonus": 10,
  "score":    5,
]),
(["quest":     "澄信罗汉",
  "quest_type": "杀",
  "time":       300,
  "exp_bonus": 40,
  "pot-bonus": 10,
  "score":    1,
]),
(["quest":    "澄和罗汉",
  "quest_type":  "杀",
  "time":      300,
  "exp_bonus": 60,
  "pot_bonus": 20,
  "score":     10,
]),
(["quest":     "澄行罗汉",
  "quest_type":  "杀",
  "time":       350,
  "exp_bonus":     50,
  "pot_bonus":  20,
  "score":      5,
]),
(["quest":    "玄苦大师",
  "quest_type":  "杀",
  "time":     500,
  "exp_bonus":   100,
  "pot_bonus":   20,
  "score":       15,
]),
(["quest":     "慧色尊者",
  "quest-type":  "杀",
  "time":      300,
  "exp_bonus":   40,
  "pot_bonus":   20,
  "score":       5,
]),
(["quest":     "慧如尊者",
  "quest_type": "杀",
  "time":       350,
  "exp_bonus":   40,
  "pot_bonus":   20,
  "score":       1,
]),
(["quest":     "宁中则",
  "quest_type":  "杀",
  "time":      500,
  "exp_bonus":  50,
  "pot_bonus":  30,
  "score":      10,
]),
(["quest":      "岳不群",
  "quest_type":  "杀",
  "time":       500,
  "exp_bonus":  60,
  "pot_bonus":   35,
  "score":      15,
]),
(["quest":      "紫檀花",
  "quest_type":  "寻",
  "time":        500,
  "exp_bonus":   30,
  "pot_bonus":   20,
  "score":      10,
]),
(["quest":    "封不平",
  "quest_type":  "杀",
  "time":      450,
  "exp_bonus":  80,
  "pot_bonus":  30,
  "score":     5,
]),
(["quest":    "成不忧",
  "quest_type":  "杀",
 "time":       500,
  "exp_bonus":  60,
  "pot_bonus":  30,
  "score":   10,
]),
(["quest":     "相国福",
  "quest_type":  "杀",
  "time":        500,
  "exp_bonus":  20,
  "pot_bonus":   10,
  "score":       10,
]),
(["quest":     "南天霸",
  "quest_type":  "杀",
  "time":       450,
  "exp_bonus":   40,
  "pot_bonus":    5,
  "score":        2,
]),
(["quest":     "秦歌",
  "quest_type":  "杀",
  "time":       300,
  "exp_bonus":  60,
  "pot_bonus":  20,
  "score":      5,
]),
(["quest":      "赵齐贤",
  "quest-type":  "杀",
  "time":       300,
  "exp_bonus":  60,
  "pot_bonus":  20,
"score":        10,
]),
(["quest":      "苗人风",
  "quest_type":  "杀",
  "time":       550,
  "exp_bonus":  70,
 "pot_bonus":    30,
  "score":      10,
]),
(["quest":        "铜哨",
  "quest_type":    "寻",
  "time":        400,
  "exp_bonus":   30,
  "pot_bonus":   10,
  "score":       2,
]),
(["quest":     "吊睛白额大虫",
  "quest_type":  "杀",
  "time":  350,
  "exp_bonus":  40,
  "pot_bonus":   20,
  "score":     10,
]),
 (["quest":       "程灵素",
  "quest_type":   "杀",
  "time":          500,
  "exp_bonus":    20,
  "pot_bonus":     5,
  "score":        2,
]),
(["quest":     "张三",
  "quest_type": "杀",
  "time":       350,
  "exp_bonus":  20,
  "pot_bonus":  10,
  "score":      3,
]),
(["quest":     "土匪头",
  "quest_type":  "杀",
  "time":       350,
  "exp_bonus":  20,
  "pot_bonus":   10,
  "score":      5,
]),
(["quest":     "霍去病",
  "quest_type":  "杀",
  "time":       100,
  "exp_bonus":  40,
  "pot_bonus":  10,
 "score":       3,
]),
(["quest":     "王百通",
  "quest_type":  "杀",
  "time":      200,
  "exp_bonus":   15,
  "pot_bonus":    10,
  "score":        1,
]),
(["quest":       "新兵",
  "quest_type":   "杀",
  "time":     300,
  "exp_bonus":     10,
  "pot_bonus":     5,
  "score":        2,
]),
(["quest":     "岗哨兵",
  "quest_type":  "杀",
  "time":        250,  
  "exp_bonus":   20,
  "pot_bonus":   10,
  "score":        3,
]),
(["quest":     "李偏将",
  "quest_type":  "杀",
  "time":      250,
  "exp_bonus":   20,
  "pot_bonus":   6,
  "score":      5,
]),
(["quest":     "王用",
  "quest_type":  "杀",
  "time":    300,
  "exp_bonus":  15,
  "pot_bonus":  5,
  "score":     5,
]),
(["quest":      "波斯长袍",
  "quest_type":  "寻",
  "time":       500,
  "exp_bonus":   10,
  "pot_bonus":    3,
  "score":         2,
]),
(["quest":    "伊梨马",
  "quest_type":  "寻",
  "time":     500,
  "exp_bonus":  15,
  "pot_bonus":    5,
  "score":      1,
]),
});
mapping query_quest()
{
return quest[random(sizeof(quest))];}

 
  
   

   
