inherit SKILL;

mapping *quest = ({
        ([      "quest":                "Ò°¹·",
                "quest_type":           "É±",
                "time":		  511,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  2,
                "score"	:	  1,
        ]),
        ([      "quest":                "åÌÒå",
                "quest_type":           "É±",
                "time":		  346,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  6,
                "score"	:	  1,
        ]),
        ([      "quest":                "Ã½ÆÅ",
                "quest_type":           "É±",
                "time":		  858,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  2,
                "score"	:	  1,
        ]),
        ([      "quest":                "ÎºÎÞ¼«",
                "quest_type":           "É±",
                "time":		  661,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  3,
                "score"	:	  1,
        ]),
        ([      "quest":                "¿àÁ¦",
                "quest_type":           "É±",
                "time":		  495,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  2,
                "score"	:	  1,
        ]),
        ([      "quest":                "Ãí×£",
                "quest_type":           "É±",
                "time":		  167,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  4,
                "score"	:	  1,
        ]),
        ([      "quest":                "µêÐ¡¶þ",
                "quest_type":           "É±",
                "time":		  321,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  4,
                "score"	:	  1,
        ]),
        ([      "quest":                "ÊÕÆÆÀÃµÄ",
                "quest_type":           "É±",
                "time":		  886,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  6,
                "score"	:	  1,
        ]),
        ([      "quest":                "Å©·ò",
                "quest_type":           "É±",
                "time":		  712,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  7,
                "score"	:	  1,
        ]),
        ([      "quest":                "ÀÏÅ©·ò",
                "quest_type":           "É±",
                "time":		  713,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  8,
                "score"	:	  1,
        ]),
        ([      "quest":                "ÆòØ¤",
                "quest_type":           "É±",
                "time":		  758,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  2,
                "score"	:	  1,
        ]),
        ([      "quest":                "·è¹·",
                "quest_type":           "É±",
                "time":		  600,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  4,
                "score"	:	  1,
        ]),
        ([      "quest":                "×íºº",
                "quest_type":           "É±",
                "time":		  377,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  10,
                "score"	:	  1,
        ]),
        ([      "quest":                "Îä¹ÝµÜ×Ó",
                "quest_type":           "É±",
                "time":		  515,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  5,
                "score"	:	  1,
        ]),
        ([      "quest":                "éÔ·ò",
                "quest_type":           "É±",
                "time":		  585,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  8,
                "score"	:	  1,
        ]),
        ([      "quest":                "ÍõÌú½³",
                "quest_type":           "É±",
                "time":		  845,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  9,
                "score"	:	  1,
        ]),
        ([      "quest":                "¶Å¿í",
                "quest_type":           "É±",
                "time":		  793,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  7,
                "score"	:	  1,
        ]),
        ([      "quest":                "Áø»æÐÄ",
                "quest_type":           "É±",
                "time":		  706,
                "exp_bonus"	:	  6,
                "pot_bonus"	:	  6,
                "score"	:	  1,
        ]),
        ([      "quest":                "ÑîÕÆ¹ñ",
                "quest_type":           "É±",
                "time":		  411,
                "exp_bonus"	:	  6,
                "pot_bonus"	:	  4,
                "score"	:	  1,
        ]),
        ([      "quest":                "Àî»ðÊ¨",
                "quest_type":           "É±",
                "time":		  260,
                "exp_bonus"	:	  8,
                "pot_bonus"	:	  9,
                "score"	:	  1,
        ]),
        ([      "quest":                "Áõ°²Â»",
                "quest_type":           "É±",
                "time":		  432,
                "exp_bonus"	:	  25,
                "pot_bonus"	:	  7,
                "score"	:	  1,
        ]),
        ([      "quest":                "°²Ï§åÇ",
                "quest_type":           "É±",
                "time":		  883,
                "exp_bonus"	:	  205,
                "pot_bonus"	:	  22,
                "score"	:	  1,
        ]),
});
mapping query_quest()
{
  return quest[random(sizeof(quest))];
}
