inherit SKILL;

mapping *quest = ({
        ([      "quest":        "æﬁ–Õ»Æ",
                "quest_type":   "…±",
                "time":         150,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        14,
        ]),                  
        ([      "quest":        "∞◊“¬Œ‰ ø",
                "quest_type":   "…±",
                "time":         250,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        14,
        ]),                  
        ([      "quest":        "∫Ï“¬Œ‰ ø",
                "quest_type":   "…±",
                "time":         250,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        14,
        ]),                  

        ([      "quest":        "ÃÏ–∞ª¢",
                "quest_type":   "…±",
                "time":         150,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        14,
        ]),                       
	([	"quest":	"’≈∞ŸÕÚ",
		"quest_type":	"…±",
                "time":         150,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        14,    
	]),


	([	"quest":	"«‡“¬Œ‰ ø" ,
		"quest_type":	"…±",
                "time":         350,
                "exp_bonus":    40,
                "pot_bonus":    10,
                "score":        14,    
	]),

	([	"quest":	"Ã∆»˝–«",
		"quest_type":	"…±",
                "time":         340,
                "exp_bonus":    80,
                "pot_bonus":    20,
                "score":        28,    
	]),

	([	"quest":	"π´ÀÔ∂œ",
		"quest_type":	"…±",
                "time":         450,
                "exp_bonus":    80,
                "pot_bonus":    15,
                "score":        23,    
	]),

	([	"quest":	"∞„»Ùæ≠",
		"quest_type":	"—∞",
                "time":         450,
                "exp_bonus":    40,
                "pot_bonus":    30,
                "score":        28,    
	]),

	([	"quest":	"—’Œ•",
		"quest_type":	"…±",
                "time":         350,
                "exp_bonus":    50,
                "pot_bonus":    10,
                "score":        19,    
	]),

	([	"quest":	"œÿ≥«πŸ±¯",
		"quest_type":	"…±",
                "time":         50,
                "exp_bonus":    20,
                "pot_bonus":    5,
                "score":        3,    
	]),

	([	"quest":	"Œ‰πŸ",
		"quest_type":	"…±",
                "time":         100,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        13,    
	]),
       ([      "quest":        "ª€’Ê◊’ﬂ",
                "quest_type":   "…±",
                "time":         400,
                "exp_bonus":    90,
                "pot_bonus":    30,
                "score":        14,
        ]),          
       ([      "quest":        "ª€∫œ◊’ﬂ",
                "quest_type":   "…±",
                "time":         400,
                "exp_bonus":    90,
                "pot_bonus":    30,
                "score":        14,
        ]),          

        ([      "quest":        "Õı∫·",
                "quest_type":   "…±",
                "time":         300,
                "exp_bonus":    70,
                "pot_bonus":    20,
                "score":        22,
        ]), 
        ([      "quest":        "Œ‚ÀƒπÛ",
                "quest_type":   "…±",
                "time":         400,
                "exp_bonus":    50,
                "pot_bonus":    20,
                "score":        32,
        ]),         
        ([      "quest":        "“Æ¬…ª˘",
                "quest_type":   "…±",
                "time":         250,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        16,
        ]),                     
        ([      "quest":        "œÁ È",
                "quest_type":   "—∞",
                "time":         250,
                "exp_bonus":    30,
                "pot_bonus":    10,
                "score":        16,
        ]),        
     
        ([      "quest":        "—Ó–°¥®",
                "quest_type":   "…±",
                "time":         250,
                "exp_bonus":    60,
                "pot_bonus":    20,
                "score":        16,
        ]),        
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}          
