inherit SKILL;

mapping *quest = ({
        ([      "quest":        "ËµÂÉ",
                "quest_type":   "Ñ°",
                "time":         260,
                "exp_bonus":    40,
                "pot_bonus":    10,
                "score":        14,      
	]),
	([	"quest":	"ÆßÐÇ·­ÔÆÑ¥",
		"quest_type":	"Ñ°",
                "time":         450,
                "exp_bonus":    50,
                "pot_bonus":    12,
                "score":        14,    
	]),
        ([      "quest":        "³Î¼Å",
                "quest_type":   "É±",
                "time":         360,
                "exp_bonus":    90,
                "pot_bonus":    30,
                "score":        14,
        ]),             
        ([      "quest":        "³ÎÃð",
                "quest_type":   "É±",
                "time":         360,
                "exp_bonus":    90,
                "pot_bonus":    30,
                "score":        14,
        ]),             
        ([      "quest":        "³ÎÊ¶",
                "quest_type":   "É±",
                "time":         450,
                "exp_bonus":    90,
                "pot_bonus":    30,
                "score":        14,
        ]),             

	([	"quest":	"»Û¿Õ×ðÕß",
		"quest_type":	"É±",
                "time":         400,
                "exp_bonus":    50,
                "pot_bonus":    20,
                "score":        14,    
	]),

	([	"quest":	"°×ÁÛ±ùÁú",
		"quest_type":	"É±",
                "time":         400,
                "exp_bonus":    60,
                "pot_bonus":    20,
                "score":        23,    
	]),

	([	"quest":	"ºÚ¹Ú¾Þòþ",
		"quest_type":	"É±",
                "time":         250,
                "exp_bonus":    50,
                "pot_bonus":    10,
                "score":        18,    
	]),

	([	"quest":	"°×Ó§¹Ú",
		"quest_type":	"Ñ°",
                "time":         250,
                "exp_bonus":    50,
                "pot_bonus":    10,
                "score":        28,    
	]),
       ([      "quest":        "³ÎË¼",
                "quest_type":   "É±",
                "time":         450,
                "exp_bonus":    90,
                "pot_bonus":    30,
                "score":        14,
        ]),          
       ([      "quest":        "³Î¹Û",
                "quest_type":   "É±",
                "time":         450,
                "exp_bonus":    90,
                "pot_bonus":    20,
                "score":        14,
        ]),          
	([	"quest":	"è¨Â×",
		"quest_type":	"É±",
                "time":         450,
                "exp_bonus":    80,
                "pot_bonus":    30,
                "score":        19,    
	]),

	([	"quest":	"ÐéÁé",
		"quest_type":	"É±",
                "time":         450,
                "exp_bonus":    75,
                "pot_bonus":    20,
                "score":        30,    
	]),

        ([      "quest":        "Íõºá",
                "quest_type":   "É±",
                "time":         300,
                "exp_bonus":    50,
                "pot_bonus":    10,
                "score":        22,
        ]), 
        ([      "quest":        "ºÚ²¼µÀÅÛ",
                "quest_type":   "Ñ°",
                "time":         300,
                "exp_bonus":    70,
                "pot_bonus":    10,
                "score":        32,
        ]),         
        ([      "quest":        "³ÎÉÐ",
                "quest_type":   "É±",
                "time":         370,
                "exp_bonus":    80,
                "pot_bonus":    36,
                "score":        16,
        ]),           
        ([      "quest":        "ËÎÔ¶ÇÅ",
                "quest_type":   "É±",
                "time":         370,
                "exp_bonus":    90,
                "pot_bonus":    30,
                "score":        16,
        ]),           
        ([      "quest":        "ÓáÁ«ÖÛ",
                "quest_type":   "É±",
                "time":         350,
                "exp_bonus":    100,
                "pot_bonus":    30,
                "score":        16,
        ]),                      
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}          
