inherit SKILL;

mapping *quest = ({
([      "quest":                "°Ë½Ç´¸",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               10
        ]),

([      "quest":                "Ø°Ê×",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               10
        ]),

([      "quest":                "·ÉïÚ",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               10
        ]),

         ([      "quest":                "Ë®½È",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               10
        ]),
 
         ([      "quest":              "´àÆ¤¿¾Ñ¼",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               10
        ]),

          ([      "quest":                "Ç®",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               10
        ]),

        ([      "quest":                "ÆòØ¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               10
        ]),
        ([      "quest":                "·è¹·",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               20
        ]),
        ([      "quest":                "Ò°¹·",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               20
        ]),
        ([      "quest":                "×íºº",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "Å©·ò",
                "quest_type":           "É±",
                "time":                 900,
                "exp_bonus":            40,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "¾ÉÊé",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "²ÝÐ¬",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "¶Å¿í",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               20
        ]),
        ([      "quest":                "ÀÏÊó",
                "quest_type":           "É±",
                "time":                 900,
                "exp_bonus":            40,
                "pot_bonus":            40,
                "score" :               20
        ]),
       ([      "quest":                "ÊÕÆÆÀÃµÄ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
       ([      "quest":                "ÍõÌú½³",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
       ([      "quest":                "ÎºÎÞ¼«",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               20
        ]),
       ([      "quest":                "Îä¹ÝµÜ×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               20
        ]),
       ([      "quest":                "éÔ·ò",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               20
        ]),
        ([      "quest":                "Ìú¸«",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "Ìú´¸",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "·Éµ¶",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "ºûµû",
                "quest_type":           "É±",
                  "time":            100,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "ÀîÊ¦Ê¦",
                "quest_type":           "É±",
                "time":                 900,
                "exp_bonus":            40,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "±¦¹Ù",
                "quest_type":           "É±",
                "time":                 900,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
       ([      "quest":                "Éþ×Ó",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "ÆÆ½£",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "·Ûºì³ñÉÀ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "Îèµû²ÊÉÀ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "°ü×Ó",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":            10,
                "pot_bonus":            5,
                "score" :               10
        ]),
        ([      "quest":                "µêÐ¡¶þ",
                "quest_type":           "É±",
                "time":                 900,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               300
        ]),
        ([      "quest":                "ËïÎò¿Õ",
                "quest_type":           "É±",
                "time":                 900,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               300
        ]),
        ([      "quest":                "·è¹·",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               300
        ]),
        ([      "quest":                "ÎÔÁú¸ÚÇ¿µÁ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               300
        ]),
       ([      "quest":                "Öñ½£",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "Ï¸½£",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "³¤½£",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "´ó»¹µ¤",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "Å£Æ¤¶Ü",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            5,
                "score" :               30
        ]),
       ([      "quest":                "Æ¤±Þ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            5,
                "score" :               30
        ]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
