#include <ansi.h>
inherit SKILL;

mapping *quest = ({
        ([      "quest":        "»Æ°Ô" ,
                "quest_type":   "É±",
                "time":         250,
                "exp_bonus":    40,
                "pot_bonus":    10,
                "score":        18,
        ]),              
        ([      "quest":      YEL  "ÄÏÌì°Ô" NOR ,
                "quest_type":   "É±",
                "time":         350,
                "exp_bonus":    30,
                "pot_bonus":    10,
                "score":        18,
        ]),                        
	([	"quest":	"ÍÁ·ËÊ×Áì",
		"quest_type":	"É±",
                "time":         150,    
                "exp_bonus":    30,
                "pot_bonus":    10,
                "score":        18,   
	]),

	([	"quest":	"[31mÎÞÇéµ¶[2;37;0m",
		"quest_type":	"Ñ°",
                "time":         250,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        18,    
	]),

	([	"quest":	"°à²ìÄÇ",
		"quest_type":	"É±",
                "time":         350,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        18,    
	]),

	([	"quest":	"Ë®ÑÌ¸óË¾ÊÂ",
		"quest_type":	"É±",
                "time":         150,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        13,    
	]),

	([	"quest":	"Ë®ÑÌ¸óË¾ÊÂ¹Ó",
		"quest_type":	"Ñ°",
                "time":         50,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        8,    
	]),

	([	"quest":	"Çúð¥ç÷",
		"quest_type":	"É±",
                "time":         220,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        26,    
	]),

	([	"quest":	"»ðß¡",
		"quest_type":	"Ñ°",
                "time":         150,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        13,    
	]),

	([	"quest":	"ÌúÉÈ½£",
		"quest_type":	"Ñ°",
                "time":         150,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        20,    
	]),

	([	"quest":	"[35mÃÔ»Ã[2;37;0m[1;35m¾­ÂÚ[2;37;0m",
		"quest_type":	"Ñ°",
                "time":         150,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        4,    
	]),

	([	"quest":	"ÓÝÇíÒÂ",
		"quest_type":	"É±",
                "time":         190,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        28,    
	]),

	([	"quest":	"[1;32mÂÌÂÞÈ¹[2;37;0m",
		"quest_type":	"Ñ°",
                "time":         150,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        14,    
	]),

	([	"quest":	"¾ÆÂ¥ÊØÎÀ",
		"quest_type":	"É±",
                "time":         150,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        14,    
	]),

	([	"quest":	"ÌÀÕÆ¹ñ",
		"quest_type":	"É±",
                "time":         150,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        12,    
	]),

	([	"quest":	"°²Ï§åÇ",
		"quest_type":	"É±",
                "time":         200,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        16,    
	]),

        ([      "quest":        "ÀÍµÂÅµ",
                "quest_type":   "É±",
                "time":         340,
                "exp_bonus":    40,
                "pot_bonus":    20,
                "score":        16,
        ]),        

	([	"quest":	"´å³¤",
		"quest_type":	"É±",
                "time":         250,
                "exp_bonus":    20,
                "pot_bonus":    10,
                "score":        25,    
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
