inherit SKILL;

mapping *quest = ({

        ([      "quest":        "Î÷·½ÔÂ",
                "quest_type":   "É±",
                "time":         350,
                "exp_bonus":    40,
                "pot_bonus":    10,
                "score":        14,
        ]),                         
        ([      "quest":        "ºìÒÂÎäÊ¿",
                "quest_type":   "É±",
                "time":         350,
                "exp_bonus":    40,
                "pot_bonus":    10,
                "score":        14,
        ]),                         

        ([      "quest":        "°×ÒÂÎäÊ¿",
                "quest_type":   "É±",
                "time":         350,
                "exp_bonus":    50,
                "pot_bonus":    10,
                "score":        14,
        ]),                         

	([	"quest":	"¶«·½ÈÕ",
		"quest_type":	"É±",
                "time":         350,
                "exp_bonus":    50,
                "pot_bonus":    20,
                "score":        14,    
	]),
        ([      "quest":        "ÕÅËÉÏª",
                "quest_type":   "É±",
                "time":         390,
                "exp_bonus":    70,
                "pot_bonus":    30,
                "score":        14,
        ]),      
        ([      "quest":        "»Û½à×ðÕß",
                "quest_type":   "É±",
                "time":         450,
                "exp_bonus":    50,
                "pot_bonus":    20,
                "score":        14,
        ]),      
        ([      "quest":        "³ÎÓû",
                "quest_type":   "É±",
                "time":         450,
                "exp_bonus":    110,
                "pot_bonus":    30,
                "score":        14,
        ]),              
        ([      "quest":        "³ÎÐÄ",
                "quest_type":   "É±",
                "time":         450,
                "exp_bonus":    100,
                "pot_bonus":    30,
                "score":        14,
        ]),              
        ([      "quest":        "°×ÁÛ±ùÁú",
                "quest_type":   "É±",
                "time":         350,
                "exp_bonus":    50,
                "pot_bonus":    40,
                "score":        14,
        ]),      
        ([      "quest":        "¾Åèº",
                "quest_type":   "Ñ°",
                "time":         250,
                "exp_bonus":    40,
                "pot_bonus":    20,
                "score":        14,      
	]),
        ([      "quest":        "°ãÈô¾­",
                "quest_type":   "Ñ°",
                "time":         350,
                "exp_bonus":    40,
                "pot_bonus":    10,
                "score":        14,
        ]),                       
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}          
