inherit SKILL;

mapping *quest = ({
	([	"quest":	"À¶Ð¡µû",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;36mÐå»¨Õë[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÑÕ»ÛÈç",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31mÎº²»»Ú[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"[33mÍõÌú½³[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"ÀÏ°åÄÐÈË",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"¶¾Ò©ïÚ",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÃÜº¯",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"°ü×Ó",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"»¤É½Ê¹Õß",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"·èÀÏÍ·×Ó",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"Ì«Òõ°ËØÔÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"À¶ÓêÃ·",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[32m»¤Ôº[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÑÆÆÍ",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"°ÍÒÀ",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"ÉÏ¹ÙîÚôá",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"±ùÓñ½äÖ¸",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"Àî°×",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"¸Ö½£",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"ÓÎÏÀ¶ù",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÑïÖÐË³",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"´÷×Ú",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÇØ±¨¹ú",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÍÐ²§É®",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"Áø»æÐÄ",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÄÂÍ¬",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;33m³ÈÒÂÉÙÅ®[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m³ÈÐ¬[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m³Èïí[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m³ÈÒÂ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m³È´ø[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m³ÈÃ±[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m³È½í[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ºÚ¹Ú¾Þòþ",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"¶­ÆÓÉú",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"½­°ÙÊ¤",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"¼ûÇ®¿ª",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"Íõ¶þÂé",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"[31mÒ°Öí[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"Ñ²²¶",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"ÐþÍ´´óÊ¦",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"»¤·¨ôÂôÄ",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"ÅýÅÃ¹í",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÓñÊ¯ÅýÅÃ",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"°¢×Ï",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"ÇåÐÄÉ¢",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"¹«Æ½×Ó",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"¹Ù±ø",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"Ö´·¨É®±ø",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"¾ü·þ",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"ôÃÍò¼Ò",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÉÒ¹«",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"´¬¸Ý",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;37mÑ©É½·ÉºüÀê[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"Ðã²Å",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"º£¹«¹«",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"Ð¡¶Ó³¤",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"ÀÏ¶Ó³¤",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"ºÎÊ¦ÎÒ",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÀîËÄ",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"[33mÌË×ÓÊÖ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"ÇØÓñ",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"ÍÁ·ËÀÏ´ó",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"½âÍò¸£",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"³¤Ç¹",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"ÃÎÓñÂ¥",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"»Æ½ðÁîÅÆ",
		"quest_type":	"Ñ°",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"Á·¹¦µÜ×Ó",
		"quest_type":	"É±",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
