inherit SKILL;

mapping *quest = ({
	([	"quest":	"[31mÃ½ÆÅ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"Àî¸«Í·",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"Áø´¾·ç",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"ÀÇÆ¤Ñ©Ñ¥",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"°×Ó§¹Ú",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"Ë¿³ñÂí¹Ó",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"³ÎºÍ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎÐÅ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"ÓáÁ«ÖÛ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"Éñ¸«Á¦Ê¿",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31mÐû»¨¾Þ¸«[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"ëüëÊ¹íÓ°",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"ÎÚÌ´Ä¾µ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"³ÎÁé",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎÃð",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎÉÐ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎÐÐ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎÓû",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"¿É³ÌÊ½Õ½¶·×°¼×",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"[32m·½Ìì»­êª[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"[30m½µÄ§èÆ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"[1;37mÁÁÒøÇ¹[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"ÀÏÕÅ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"³Î¼Å",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"³£ÀÏ´ó",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"Öñ¹Ü",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"ÀÇÆ¤Åû·ç",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"Â½³Ë·ç",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"×óÈ«",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"ëÙËÉ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"Ñî¿µ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"[36mÅåµ¶[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"[31mÅ®¶ùºì[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"ºÎ²»¾»",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"Ðþ´È´óÊ¦",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"±«´ó³þ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"ÂÞÁÒ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"ÉÏ¹ÙÔÆ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"É£ÈýÄï",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"Íõ³Ï",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"¸ðÍ£Ïã",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"³¤êª",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"Í¯°ÙÐÜ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"¼Ö²¼",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"ÁÖ¼É",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"ÈýÇåÉñ¹Ú",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"ÌìÊ¦µÀÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"ÆßÐÇ·­ÔÆÑ¥",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31mÖä½£Íõ¡õ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"ÐþÖÇºÍÉÐ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"´óºìôÂôÄ",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"[35mÑîÅÅ·ç[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"ÑÏÍ¢Òó",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;37m¦×ÆÆ ²Ð Ææ ½£¦×[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[31m»ð ÔÆ [1;34mÕ½ ¼×[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"ÅË¾üìø",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;37mÐ°½£´©Áé[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"ÌúÖÐÌÄ",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"Ïô±Ù³¾",
		"quest_type":	"É±",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;36m´µÑ©²ÐÔÆÑ¥[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;36m´µÑ©²ÐÔÆÒÂ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;36m´µÑ©²ÐÔÆ´ø[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;36m´µÑ©²ÐÔÆ½í[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"ÌúÑª´óÆì",
		"quest_type":	"Ñ°",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
