inherit SKILL;

mapping *quest = ({
	([	"quest":	"[35mòşÉß[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31mÁÖÀÏ°å[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"Ë®ÑÌ¸óºìÒÂÎäÊ¿",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"Å£Æ¤Ñ¥",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"Ë®ÑÌ¸óÎäÊ¿ë©",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"ÏÊºì½ğÎÚ¹Ú",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"ÏôÉı",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ÌìĞ°»¢",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ÏôÏô",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"Â½µÃ²Æ",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"Çå·¨±ÈÇğ",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"ËşÉ®",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ÉáÀû×Ó",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32m³ÌÁéËØ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"Òõ±ö",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"µÀ³¾ìøÊ¦",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"µÀÒ»ìøÊ¦",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"[1;31mÇáºìÂŞÒÂ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31mÇáºìÂŞÉ´[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ËïÌìÃğ",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"Äª²»ÊÕ",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ÀîÄª³î",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"·÷³¾",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"ÇàÉ«µÀÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"°¢ÉÆ",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"[32mÂÌÒÂÉÙÅ®[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32mÂÌĞ¬[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32mÂÌïí[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32mÂÌÒÂ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32mÂÌ´ø[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32mÂÌÃ±[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32mÂÌ½í[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"µÀ³ÉìøÊ¦",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"¿ì»îÈı",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ÇàÒÂÎäÊ¿",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"Ìú¼×",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"´ó¶Ó³¤",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"ÇàÍ­Õ½¿ø",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"ÃçÓôÊÖ",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"×êÊ¯ĞØÕë",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"¶ú»·",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ÑÕÔ«",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"»ÆÉ«³¤ÉÀ",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"ÔÀÁéÉº",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"ÂÌÉ«³¤È¹",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"·ëÌú½³",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"ÉÕºìµÄÌú´¸",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"µÀ¾õìøÊ¦",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"[35m×ÏÒÂÉÙÅ®[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m×ÏĞ¬[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m×Ïïí[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m×ÏÒÂ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m×Ï´ø[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m×ÏÃ±[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m×Ï½í[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ÕÅÈı",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"ÃÉÃæÍ·ÕÖ",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"µÀ¹ûìøÊ¦",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"µÀÏàìøÊ¦",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"ÊØËÂÉ®±ø",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"´¾ÓÚ»³Ì«",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"ÉßÁÛÆ¤±Ş",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"À¶óãŞ±",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ÕÑÈØ",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ÓñÖñ½£",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"Òø³á½ğô¢",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[36mÇàç±³ñÈ¹[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"½ğÒÇÍ®",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;35mÕäÖéÏî¡õ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"ĞĞÕß",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"ÁúÉØÒ÷",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"Îä½«",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"¹ÈĞéµÀ³¤",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"µÀÆ·ìøÊ¦",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"ÀÏ°å",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"Ğ¡ÕÑ",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"[33mÀÏ»¢[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
