inherit SKILL;

mapping *quest = ({
	([	"quest":	"Âô±ý´óÊå",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ç¬±ñÀÏÌ«ÆÅ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÂôÌÇºùÂ«µÄ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Âô°ü×ÓµÄ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¹Ù¼ÒÐ¡½ã",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¸¾ÈË",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ñ¾¡õ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÊéÉú",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÂìÒÏ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ºûµû",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"òÐòÐ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"´óÀÏÊó",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÐÅ¸ë",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ð¡¾ê",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"²ÔÓ¬",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÀîÊ¦Ê¦",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"²èÒ¶",
		"quest_type":	"Ñ°0",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"²è²©Ê¿",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"×íºº",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¹¤½³µÄÐ¡º¢",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ð¡º¢",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÀÏ¹«¹«",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÀÏÆÅÆÅ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÉòÍòÄê",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¹¤½³",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"²ÉÊ¯¹¤",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÆòØ¤",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ëþ×£",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÊÕÆÆÀÃµÄ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"éÔ·ò",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31mÀÏ°å[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[35mÀðÓã[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"µêÐ¡¶þ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ó¤¶ù",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÀÏ°åÄï",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"°Ü¼Ò×Ó",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Å©Ãñ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33mÂô»¨Ð¡Å®º¢[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÇàÒÂ¼ÒÈË",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33mµêÐ¡¶þ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¸ðÁù",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÀÏÊóÈâ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Å©·ò",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ãí×£",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ã½ÆÅ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÎºÎÞ¼«",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¿àÁ¦",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[30mµêÐ¡¶þ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[35mÐ¡··[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"³¤½£",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Çà²¼É®ÒÂ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Óæ·ò",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÎÞÃû·òÈË",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ð¡··",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Å®º¢",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"ÀÏÅ©·ò",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"Ð¡ºï",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"[30mÐ¡ºï[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"ÀÏ´óÄï",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"Îä¹ÝµÜ×Ó",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"Î¬Îá¶û×å¸¾Å®",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"¾ÉÊé",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"´Ö²¼ÒÂ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"²¼ÒÂ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"Å£Æ¤¾Æ´ü",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"ËòÒÂ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"²ÝÐ¬",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"°×É«µÀÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"³¤½£",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"É¸×Ó",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ìú¡õ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ºÚÉ«³¤ÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÇáÂÞ³ñÉÀ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Òøô¢",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"²Ëµ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÌÕºø",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ø°Ê×",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"·Ûºì³ñÉÀ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"´óºì³ñÉÀ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¡¸¾Åèº¡¹",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¼ÞÒÂÉñ¹¦",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"·Ûºì²¼ÉÀ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÆÆÀÃµÄ·Ûºì²¼ÉÀ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ìú¸«",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Î¬Îá¶û×å³¤ÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"[33mä½É´Å®º¢[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[32mÎè¼§[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ä°ÉúÈËºî±ª",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ð¡Í¯",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"æ¾Å®",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33mÅ®º¢[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¼ÅÎ¢",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Çîºº",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"ÀÏÊó",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"ÃÛ·ä",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"³ñÒÂ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[35mÉ´[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"²¼È¹",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÄÐº¢",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"¹Â»êÒ°¹í",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"´å³¤",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ò°¹·",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31mÅ®º¢[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31mµêÐ¡¶þ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ñ¾÷ß",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"½øÏã¿Í",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33mÓÎÈË[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33mÐÐÈË[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[30m¸¾ÈË[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ð¡°×ÍÃ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ð¡ÃÛ·ä",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"´ÓÊÙÒÂËºÏÂµÄ²¼Ìõ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"×¯×Ó",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"ÎÚÑ»",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÇÇÈý»±",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ìô·ò",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"É³³æ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Å©¸¾",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"¶¾Éß",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"´ä»¨",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"ÍõÌú½³",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"Ìú´¸",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"³Â°¢ÆÅ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"ÌÀÕÆ¹ñ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¼Ò¶¡",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÁøÓñ¶ù",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"½ðË¿È¸",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ð¡½ðÊó",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ò°ÍÃ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¸òó¡",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¾»±¯",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"¾»¿à",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"¾»ÄÑ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"¾»Í´",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"[31mµãµã[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"°×ÓñÅýÅÃ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÆÝËÄ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31mºìÒÂÉÙÅ®[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"¾»´È",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"[31m´óÀÏÊó[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"[31mºìÐ¬[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31mºìïí[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31mºìÒÂ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31mºì´ø[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31mºìÃ±[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31mºì½í[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"½¹Î²ÇÙ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÃÀ²ÏÄï",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"Ö©Öë",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"·è¹·",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ð¡Á÷Ã¥",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"Ð¡à¶ÂÞ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"ÍÁ·Ë",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"¶Ì½£",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"²è¹¤",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"²èÒ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"Æ¤ÒÂ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"Ð¡Ñò¸á",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"Ä°ÉúÈËÂ½Ò»Äï",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÓÎ¿Í",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"[33mÐ¡Â¹[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"³¤±Þ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"»ï¼Æ",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"²ÉÒ©ÈË",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"ÌìÉ½Ñ©Á«",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"Ò©³ú",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"Å®Ó¶ÈË",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"¼¦Ã«",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"´óÀÇ¹·",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"ÔÓ»õ··",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"·ÉïÚ",
		"quest_type":	"Ñ°",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"µØÆ¦",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"Ð¡ÍÁ·Ë",
		"quest_type":	"É±",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
