inherit SKILL;

mapping *quest = ({
	([	"quest":	"»¤Ôº",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"ÈÙÓÐÂ»",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"É±Öíµ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"Àî»ðÊ¨",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"·áÓÐ¸£",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"¿×³¤Éú",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"µÀÊ¿",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"ÎÔÁú¸ÚÇ¿µÁ",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"¹íÍ·µ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"ÌÒÄ¾½£",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"[1;35mÅ£¶þ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"[1;35mÌÇÈËÍõ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"[1;35mÖì°¢Ïã[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"[31mÃçÈôÀ¼[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"Óü×ä",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"¾Þ¾¨°ï°ïÖÚ",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"¸Öµ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"ºÚÎÞ³£",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"°×ÎÞ³£",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"²¨Ë¹ÉÌÈË",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"²¨Ë¹³¤ÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"°¢À­²®Íäµ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"°¢·²Ìá",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"ÀîÌú×ì",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"¶¬²»À­",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"µ¶¿Í",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"²É»¨×Ó",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;37mïÚ¾ÖµÜ×Ó[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"[31mÖñµ¶[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"±øÆ÷··×Ó",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"Á÷Ã¥Í·",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"Âô»¨¹ÃÄï",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"²ÊÒÂÉÙÅ®",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"Îèµû²ÊÉÀ",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"·÷Áø±Þ",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"Áõ°²Â»",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"µ¥µ¶",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"ÁøÔÆÌì",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"Áõ¶þÄï",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"ÍÁ·ËÍ·",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"ÃÉÃæÈË",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"»¯ÔµºÍÉÐ",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"Öª¿ÍÉ®",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"Ë®ÑÌ¸óÎäÊ¿",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"ÏÊºì½õÒÂ",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	-1,
	]),

	([	"quest":	"[34mÀ¶ÒÂÉÙÅ®[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"[34mÀ¶Ð¬[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"[34mÀ¶ïí[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"[34mÀ¶ÒÂ[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"[34mÀ¶´ø[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"[34mÀ¶Ã±[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"[34mÀ¶½í[2;37;0m",
		"quest_type":	"Ñ°",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

	([	"quest":	"[30m»¨»¨¹«×Ó[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	50,
		"shen_type":	0,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
