inherit SKILL;

mapping *quest = ({
	([	"quest":	"ÖÜÂ¡Òæ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"Îå¹É¸Ö²æ",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"[33m×óÇáºò[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ÀîÍ¬",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"³ÂÍò²ý",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"Òø´¸",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"Î÷·½ÔÂ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"¶«·½ÈÕ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ÕÅËÉÏª",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"°×ÒÂÎäÊ¿",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"»Û¿Õ×ðÕß",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"»ÛÈç×ðÕß",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ìøÕÈ",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ÁõÀÏÅ©",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"[33mÂí¿É²¤ÂÜ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"Ê¥¾­",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"[33m½­Ð¡´¨[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ÌìÀÇ×Ó",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"¸ÖÕÈ",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;37m·çÈª½£Áé[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"[33m³óµñ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ÊØ³Ç¹Ù±ø",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ÏØ³Ç¹Ù±ø",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ÖÆ·þ",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"½­ÉÏÓÎ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ÁúÖÛ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"»ÆÈØ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"[32mºØÖªÕÂ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"»ÛÐÞ×ðÕß",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"Ç®ÑÛ¿ª",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"»Û½à×ðÕß",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"[1;37m°¢Ðå[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ÆëÃ¼¹÷",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ÎºÎÞË«",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"Îä¹Ù",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"»ÛÐé×ðÕß",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"Å·Ñô·æ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"³ö³¾×Ó",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"»ÛºÏ×ðÕß",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ÕÅ¸»Í¬",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"¸ßÀÏÕß",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"°«ÀÏÕß",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"»ÛÕæ×ðÕß",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ÕªÐÇ×Ó",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"ËÎÔ¶ÇÅ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"Ïà¹ú¸£",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"³Î¹Û",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"³Î¼á",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"³Î¾»",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎÃ÷",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎÊ¶",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎË¼",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎÐÄ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎÖ¾",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"½ð±ßºÚ²¼ôÂôÄ",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ÖìÔå",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"Æ½Ò»Ö¸",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"[31mÒ©Íõ[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ÂéÒÂ",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"Ò»Ç§Á½ÒøÆ±",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ÄªÐÀ·¼",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"Öììä",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"[33mÁúÎå[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"[32mÃçÈË·ï[2;37;0m",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"¶«±±»¢",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"Ê·ÊØ²Æ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"ÐÏÇ§»Û",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"°×ÅÛ¹«",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ºÚÅÛ¹«",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ºÚÆå×Ó",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"°×²¼ÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ºÚ²¼ÅÛ",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"°×Æå×Ó",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"¾ÆÈâºÍÉÐ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ÓÍ¹¸°ß°ßµÄÉ®ÒÂ",
		"quest_type":	"Ñ°",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"ÀîÐÅ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),

	([	"quest":	"³ÎÒâ",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"³ÎÖª",
		"quest_type":	"É±",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
